"""Agregar campo notas a Emprendimiento

Revision ID: 105a0bf4ef94
Revises: 5115e48456fd
Create Date: 2024-06-13 14:40:48.685981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105a0bf4ef94'
down_revision = '5115e48456fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('redes_sociales',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('emprendimiento', schema=None) as batch_op:
        batch_op.alter_column('run',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('nombre_emprendimiento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('razon_social',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('nombre_representante',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('provincia',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('comuna',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint('emprendimiento_run_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprendimiento', schema=None) as batch_op:
        batch_op.create_unique_constraint('emprendimiento_run_key', ['run'])
        batch_op.alter_column('estado',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('comuna',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('provincia',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre_representante',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('razon_social',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('nombre_emprendimiento',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('run',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    with op.batch_alter_table('detalle', schema=None) as batch_op:
        batch_op.alter_column('redes_sociales',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('logo',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('notas')

    # ### end Alembic commands ###
