"""Add estado column to Emprendimiento

Revision ID: 45b0592a4c51
Revises: 
Create Date: 2024-06-04 07:46:47.539240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b0592a4c51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprendimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=5), nullable=True))
        batch_op.create_unique_constraint(None, ['rut'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprendimiento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
